### ISSUE TITLE
This TweetDeck Enhancer "Plus" is heavily bloated

### ISSUE THREAD

**Issue by dangeredwolf** [jumono/TweetdeckEnhancerPlus#2]
8.8 MB packed? 10.4 MB unpacked? really?
TweetDeck Enhancer 5.0.6, which includes everything inside it from images, to sounds, etc. is only 497 KB packed and 1 MB unpacked.

Yours should not be 17x larger than mine, as yours has less features than mine.

(FYI, your codename "Liberty" is a stupid code name because 5.0.5 and 5.0.6 still does *not* track you)

**Comment by jumono** [comment]
TweetDeck Enhancer Plus has been unbloated.
