### ISSUE TITLE
Don't serve files from raw.github.com

### ISSUE THREAD

**Issue by mkody** [jumono/TweetdeckEnhancerPlus#3]
Prefer using https://rawgit.com/ (or you can get blacklisted by Github)

So, for exemple, `https://raw.githubusercontent.com/jumono/TweetdeckEnhancerPlus/master/assets/assets/back.png` 
becomes 
`https://cdn.rawgit.com/jumono/TweetdeckEnhancerPlus/master/assets/assets/back.png`

**Comment by jumono** [comment]
Thanks for the tip :+1:
