### ISSUE TITLE
Reorganisation 

### ISSUE THREAD

**Issue by dangeredwolf** [jumono/TweetdeckEnhancerPlus#4]
If you're still not aware, the last TDE releases removes the anonymous activation system entirely. After the DDoS, the activation server kept up for legacy TDE client reasons was also mostly shut down. Analytics are still collected by default, and they're completely anonymous, respect user privacy, only include user agent (OS / browser) and TDE version to better understand what people are using. It's relatively easy to switch off all analytics yourself if you'd like. 

**I'm working with the devs of the more brilliant Condor fork of TDE on TDE6, a grounds up solution.**

Enhancer Verified symbols will be visually different in TDE6 than TDE5, and differentiate them even more from Twitter Verified accounts. It isn't final quite yet. We're thinking of changing it to a plus instead, and even having different classes of Enhancer Verified symbols, which will be pretty neat. 

Also in the latest TDE 5 releases, you can disable remote hotfixes and enhancer verified as well, if you'd like. 

The primary developer even told me, after I explained to him how it actually worked, that he way overreacted about the TDE5 analytics system. It's in place only to improve user experience in the long run, and is well documented in the privacy policy. As I've said, it's easy to disable. 

In TDE6 we're going to rebuild basically the entire thing, grounds up, for way better performance and stability than ever before. And I'd be willing to have you join our collaborative work, to deliver the best user experience, as well as user control over the extension. And user features as well. When it first starts it will allow you to disable analytics right off the bat without having to manually disabling it later. And it'll be tons better than TDE, TDEP, and Condor has ever been able to deliver. 

**If you do not wish to join the project for a better TweetDeck Enhancer, or you are not going to be mature about it** (like you've always seemed to be in my ~1 week of knowing you), just know that **your extension's structure will be heavily obsolete in the very near future**, worsen the user experience, and waste valuable performance that TDE 5.0.6 and Condor have both already improved upon compared to yours, and will greatly improve in TDE6. 

Yes, TDE6 will replace TDE5 completely, and as far as I know will also replace Condor now that the 3 of us are working on it together. TDE6 will be a collaborative effort. That's why I'm wondering if you're interested.

**Comment by jumono** [comment]
Thanks for your offer Ryan and I'll actually think about it before accepting it but there's some chance that i accept it.

**Comment by dangeredwolf** [comment]
Alright. You can iMessage me ryan@ryandolan123.com Or telegram me @dangered if you'd like.
